# models.py
from django.db import models

class Response(models.Model):
    # Choices for the status of the response
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    prompt = models.TextField(help_text="Prompt provided to the AI model.")
    response_text = models.TextField(help_text="Response generated by the AI model.")
    model_used = models.CharField(max_length=100, help_text="AI model used to generate the response.")
    timestamp = models.DateTimeField(auto_now_add=True, help_text="Time the response was generated.")
    status = models.CharField(
        max_length=20, 
        choices=STATUS_CHOICES, 
        default='pending',
        help_text="Current status of the AI response."
    )
    processing_time = models.FloatField(help_text="Time taken by the model to process the prompt.")

    class Meta:
        # Default ordering for querysets: most recent response first
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['timestamp']),
        ]
        
    def __str__(self):
        return f"Response {self.id} - {self.status} - {self.model_used}"
