# Generated by Django 5.0.1 on 2025-01-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Prompt provided to the AI model.')),
                ('response_text', models.TextField(help_text='Response generated by the AI model.')),
                ('model_used', models.CharField(help_text='AI model used to generate the response.', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time the response was generated.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the AI response.', max_length=20)),
                ('processing_time', models.FloatField(help_text='Time taken by the model to process the prompt.')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status'], name='api_respons_status_8dcc3b_idx'), models.Index(fields=['timestamp'], name='api_respons_timesta_87928d_idx')],
            },
        ),
    ]
